import { Cohort } from "@/types";

export const cohortsList: Cohort[] = [
  {
    id: "2",
    name: "Innovate India 2024 Cohort",
    shortName: "II 24",
    startDate: "2024-04-01",
    endDate: "2024-09-30",
    description:
      "Aimed at accelerating innovation in tech startups across India, with a focus on AI and blockchain technologies.",
    startups: [
      {
        id: "4",
        companyName: "TechNova",
        industry: "AI",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
      {
        id: "5",
        companyName: "Blockify",
        industry: "Blockchain",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
      {
        id: "6",
        companyName: "QuantumLeap",
        industry: "Quantum Computing",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
    ],
    schedule:
      "The program includes workshops, networking events, and demo days, running from April to September.",
  },
  {
    id: "3",
    name: "Startup Europe 2024 Cohort",
    shortName: "SE 24",
    startDate: "2024-05-01",
    endDate: "2024-10-31",
    description:
      "Designed for tech startups across Europe, focusing on market expansion and user acquisition strategies.",
    startups: [
      {
        id: "7",
        companyName: "MarketX",
        industry: "E-commerce",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
      {
        id: "8",
        companyName: "CloudCore",
        industry: "Cloud Computing",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
      {
        id: "9",
        companyName: "HealthNet",
        industry: "HealthTech",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
    ],
    schedule:
      "The cohort includes mentoring sessions, workshops, and pitch competitions, running from May to October.",
  },
  {
    id: "4",
    name: "Asia Growth 2024 Cohort",
    shortName: "AG 24",
    startDate: "2024-06-01",
    endDate: "2024-12-31",
    description:
      "Focuses on scaling tech startups in Asia, with a particular emphasis on digital transformation and innovation.",
    startups: [
      {
        id: "10",
        companyName: "DigitalEase",
        industry: "Digital Transformation",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
      {
        id: "11",
        companyName: "FinServe",
        industry: "Fintech",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
      {
        id: "12",
        companyName: "AgriTech Solutions",
        industry: "Agritech",
        cohort: "",
        founders: [],
        description: "",
        pitchVideoLink: "",
        companyLogo: "",
        companyEmail: "",
        website: "",
        location: {
          city: "",
          country: "",
        },
        companySize: 0,
        fundraisingAmount: 0,
        valuation: 0,
        industries: [],
        founded: 0,
        pitchDeckLink: "",
        calendlyLink: "",
        status: "",
      },
    ],
    schedule:
      "The program runs from June to December, including strategic workshops, mentorship programs, and investor meetings.",
  },
];
